### ISSUE TITLE
使用常量泛型来编写该支持库

### ISSUE THREAD

**Issue by SKTT1Ryze** [nervosnetwork/bloom-filters#10]
您好，Rust 目前常量泛型语法已经基本稳定，我个人觉得常量泛型非常适合来实现 bloom filter 这种数据结构，可以做到在编译期确定 bloom filter 需要的内存空间大小，并且可以把数据放在栈上。相比该项目当前使用 Vec 数据结构的方式（数据放在堆上，并且在运行时确定 bloom filter 需要空间的大小），使用常量泛型可以减少一些运行时开销，并且可以做到数据更快查询（栈相比堆的优势）。  
但是很遗憾由于目前 Rust 常量计算不支持浮点运算，如果使用常量泛型实现，则需要用户指定 bloom filter 的 bucket 个数，而不能通过`想要插入的数据数目`和`可接受误报率`两个参数进行计算，这样会给用户带来一定的负担。  
但我仍觉得使用常量泛型实现该支持库是有必要的，于是尝试在该库的基础上实现了一版，项目地址在这里：https://github.com/SKTT1Ryze/bloom-filters/tree/const-generic
我有个想法，就是把上面的这个常量泛型的实现作为该项目的一个新分支，然后由我们共同维护，不知道作者意见如何？

**Comment by quake** [comment]
感谢你的建议, 我觉得可以将它作为一个 feature 切换在一个库里面支持,欢迎 PR.

**Comment by SKTT1Ryze** [comment]
感谢建议，pr已经提出：https://github.com/nervosnetwork/bloom-filters/pull/11
